feat(syncctl): reduce log verbosity
- Print only an excerpt of Imapsync run log.
- Keep the full last log run in a task log file.
- Use cron's FDs for output/error only if running without TTY.

diff --git a/imapsync/usr/local/bin/syncctl b/imapsync/usr/local/bin/syncctl
--- a/imapsync/usr/local/bin/syncctl
+++ b/imapsync/usr/local/bin/syncctl
@@ -15,6 +15,12 @@
 
 set -e
 
+# If stdout is not on a TTY, redirect stdout and stderr to cron's FDs
+if [ ! -t 1 ]; then
+    exec >/proc/1/fd/1
+    exec 2>/proc/1/fd/2
+fi
+
 if [[ $# -ne 2 ]];then
     echo "Usage: syncctl {start,status,stop,validate} username"
     exit 0
@@ -30,6 +36,16 @@ while IFS= read -r line; do
   # Export the variable
   export "${line?}"
 done < "/etc/imapsync/${task_id}.env"
+
+print_log_excerpt() {
+    local task_id
+    task_id=$1
+    awk -v taskid="${task_id}" \
+    -e '/^Messages transferred/ { tx=$4 }' \
+    -e '/^Exiting with return value/ { exitmsg=$0 }' \
+    -e 'END { printf("task %s: tx=%s, msg=%s\n", taskid, tx, exitmsg) }' \
+    "/etc/imapsync/${task_id}.log"
+}
 
 get_file_age_in_days() {
     local filename
@@ -84,9 +100,16 @@ if [[ "${action}" == "start" ]]; then
         ${FOLDER_INBOX} \
         ${sieve_enabled:+--sievedelivery2} \
         ${sync_unseen:+--search1=UNSEEN --setflag1=Seen --noresyncflags} \
-        --exclude '^Public$|^Shared$'"${exclude_regex}" > /proc/1/fd/1 2>&1
-        # FOLDER_INBOX must not be enquoted NethServer/dev#7296
-
+        --exclude '^Public$|^Shared$'"${exclude_regex}" \
+        >"/etc/imapsync/${task_id}.log" || \
+    {
+        exit_code=$?
+        echo "task ${task_id}: imapsync error: ${exit_code}" 1>&2
+        print_log_excerpt "${task_id}" 1>&2
+        exit ${exit_code}
+    }
+    # print run summary
+    print_log_excerpt "${task_id}"
     # set the timestamp file to the current time
     echo ${FOLDERSYNCHRONIZATION} > "/etc/imapsync/${task_id}.timestamp"
     touch -m -d "@${timestamp}" "/etc/imapsync/${task_id}.timestamp"
